---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Include variables.
      include_vars: vars/main.yml

    - name: Create user account.
      ansible.builtin.user:
        name: "{{ item.seu_name | default(omit) }}"
        comment: "{{ item.seu_comment | default(omit) }}"
        state: "{{ item.seu_state | default(omit) }}"
        shell: '{{ item.seu_shell | default(omit) }}'
      with_items: "{{ users }}"

  roles:
    - role: glillico.setup_ssh_keys
